name: example

on:
  pull_request:
    branches:
      - "**"

jobs:
  skip:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.filter.outputs.should_skip }}
    steps:
      - uses: actions/checkout@v4
        with:
          filter: blob:none
          fetch-depth: 0
      - uses: leavesster/pull-request-path-filter@v0.2
        id: "filter"
        with:
          paths: |
            - "src/**"
            - "!**.md"

  echo:
    runs-on: ubuntu-latest
    needs: skip
    if: ${{ needs.skip.outputs.should_skip == 'false' ||  github.event_name == 'workflow_dispatch' ||  github.event_name == 'schedule' }}
    steps:
      - if: ${{needs.skip.outputs.should_skip}} == 'false'
        run: echo ${{ needs.skip.outputs.should_skip}} hit
      - if: ${{ github.event_name == 'workflow_dispatch' }}
        run: echo workflow_dispatch
      - if: ${{ github.event_name == 'schedule' }}
        run: echo schedule
  
  should_skip:
    runs-on: ubuntu-latest
    needs: skip
    if: ${{ needs.skip.outputs.should_skip == 'false' }}
    steps:
      - run: echo ${{ needs.skip.outputs.should_skip }} hit